### ISSUE TITLE
Website feedback

### ISSUE THREAD

**Issue by dlsniper** [devfest-berlin/2015.devfest-berlin.de#26]
Hi, Here's a few things that I've found from going over the website:
- [x] on the logistics page, https://devfest-berlin.de/logistics/, we mention Lviv and we have the venues for that place instead of Berlin
- [x] become a speaker button appears too late on the page
- [x] homepage is loading a script which needs the feed from `http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000`.
- [x] there's a time in the location box on the homepage, what's that supposed to be for?

**Comment by stefanhoth** [comment]
Thanks for the feedback! 
- where is the logistics page linked? I disabled it in the navigation because it's not reworked yet. 
- the button appearance is a feature. I guess the idea is that it jumps into your eye when you start scrolling?! 
- yes, I mentioned this already. It's for the twitter section and we need to install our own tweet cache. 
- the time only makes sense for 1 day events and is misleading now. Just forgot to remove it. 

Should be all addressed.

**Comment by dlsniper** [comment]
> - where is the logistics page linked? I disabled it in the navigation because it's not reworked yet.

The "directions" button from the homepage in the location section, search for `/logistics/#find-way`

> - the button appearance is a feature. I guess the idea is that it jumps into your eye when you start scrolling?!

I see. The issue issue is that for some pages it doesn't appear and for some it appears when you are say 25% down the page already.

> - yes, I mentioned this already. It's for the twitter section and we need to install our own tweet cache.

Sorry, I've missed this one. If need be, I can cook up a Go app (we can make it available for other GDGs as well via AppEngine) that can be used so that PHP is not involved at all in the process (and thus deployment is easier). Let me know
